version: "3.9"

services:
  db:
    platform: linux/amd64
    image: "postgres:alpine"
    networks:
      - web
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: "db"
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    secrets:
      - db_password

  redis:
    platform: linux/amd64
    image: "redis:alpine"
    networks:
      - web
    expose:
      - 6379
    volumes:
      - cache:/data

  web:
    build: .
    depends_on:
      - db
      - redis
    expose:
      - "5001"
    networks:
      - web
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - files:/files
    environment:
      VIRTUAL_HOST: "localhost"

      REDIS_HOST: "redis"

      DB_USER: "postgres"
      DB_HOST: "db"
      DB_NAME: "db"
      DB_PASSWORD_FILE: /run/secrets/db_password
      SECRET_KEY_FILE: /run/secrets/secret_key
      PASSWORD_SALT_FILE: /run/secrets/password_salt
      SENDGRID_API_KEY_FILE: /run/secrets/sendgrid_api_key

      PYTHONUNBUFFERED: 1

      LABWARE_DIR: /files/labware
    secrets:
      - db_password
      - secret_key
      - password_salt
      - sendgrid_api_key

  worker:
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    environment:
      REDIS_HOST: "redis"

      SENDGRID_API_KEY_FILE: /run/secrets/sendgrid_api_key

      PYTHONUNBUFFERED: 1
    secrets:
      - sendgrid_api_key

  nginx:
    platform: linux/amd64
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
    environment:
      - DEFAULT_HOST=web.local
    networks:
      - web

networks:
  web:
    driver: bridge

secrets:
  db_password:
    file: db_password.txt
  secret_key:
    file: secret_key.txt
  password_salt:
    file: password_salt.txt
  sendgrid_api_key:
    file: sendgrid_api_key.txt

volumes:
  db:
    driver: local
  files:
    driver: local
  cache:
    driver: local
